name: Update Bot Files in website

on:
  push:
    paths:
      - 'bot.py'
      - 'requirements.txt'
    branches:
      - main

jobs:
  update-website:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Git config
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Check for changes in bot.py
        id: check-bot
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "bot.py"; then
            echo "bot_changed=true" >> $GITHUB_OUTPUT
          else
            echo "bot_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check for changes in requirements.txt
        id: check-req
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "requirements.txt"; then
            echo "req_changed=true" >> $GITHUB_OUTPUT
          else
            echo "req_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout website branch
        if: steps.check-bot.outputs.bot_changed == 'true' || steps.check-req.outputs.req_changed == 'true'
        run: |
          git fetch
          git checkout website
      
      - name: Update bot.py in website branch
        if: steps.check-bot.outputs.bot_changed == 'true'
        run: |
          git checkout main -- bot.py
          
          BOT_CONTENT=$(cat bot.py)
          sed -i '/<code id="source-code" class="language-python">/,/<\/code>/c\<code id="source-code" class="language-python">'$BOT_CONTENT'<\/code>' index.html
          if [ -d "docs" ]; then
            cp bot.py docs/bot.py
          fi
          echo "Updated bot.py in website files"
      
      - name: Update requirements.txt in website branch
        if: steps.check-req.outputs.req_changed == 'true'
        run: |
          git checkout main -- requirements.txt
          
          REQ_CONTENT=$(cat requirements.txt)
          sed -i '/<div class="requirements">/,/<\/div>/s/<pre><code>.*<\/code><\/pre>/<pre><code>'$REQ_CONTENT'<\/code><\/pre>/' index.html
          echo "Updated requirements.txt in website files"
      
      - name: Commit and push changes to website branch
        run: |
          git add index.html
          if [ -d "docs" ]; then
            git add docs/bot.py
          fi
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update bot code and requirements.txt from main branch"
            git push origin website
          fi
